### ISSUE TITLE
Updating requires `--greedy` flag

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/homebrew-tap#4]
Just ran into this. Not sure yet if it's a settings thing, or a cask thing.

```bash
⏺ oss/pants-plugins-cpp % brew update && brew upgrade                                                                                                                                          
Already up-to-date.

⏺ oss/pants-plugins-cpp % PANTS_BOOTSTRAP_VERSION=report pants
0.2.0

⏺ oss/pants-plugins-cpp % brew upgrade --greedy
==> Upgrading 1 outdated package:
pantsbuild/pants/pants 0.2.0 -> 0.2.1
==> Upgrading pants
==> Downloading https://github.com/pantsbuild/scie-pants/releases/download/v0.2.1/scie-pants-macos-x86_64
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/572180558/6f2c632d-5b21-409c-acc2-d7ce534e34c2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH
######################################################################## 100.0%
==> Unlinking Binary '/usr/local/bin/pants'
==> Linking Binary 'scie-pants-macos-x86_64' to '/usr/local/bin/pants'
==> Purging files for version 0.2.0 of Cask pants
🍺  pants was successfully upgraded!

⏺ oss/pants-plugins-cpp % PANTS_BOOTSTRAP_VERSION=report pants
0.2.1
```

**Comment by kaos** [comment]
Note to doc writer: when upgrading the `pants` bootstrap binary, stick with either `SCIE_BOOT=update pants` **OR** `brew update && brew upgrade pants` .. as mixing them will not play that nice (yet?)

**Comment by kaos** [comment]
Yea, the auto_update was a flag telling brew that the application has a self update mechanism.

**Comment by kaos** [comment]
which scie-pants does have.. but apparently it also means that we'll opt-out of using brew update by default...

**Comment by sureshjoshi** [comment]
Related: https://github.com/Homebrew/homebrew-cask/issues/48384

**Comment by kaos** [comment]
Good find. `brew update` will actually bork if you've used the self update. I guess you can use `--force` to ignore this, but then it will simply replace the one binary so the install will never get into a broken state.
